// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGkAFp6hLmSgkd0pjFL2xhTl0mdzo8l7A',
    appId: '1:761920059803:web:ed7dfe9b3c2a89c67b493e',
    messagingSenderId: '761920059803',
    projectId: 'zylu-employee',
    authDomain: 'zylu-employee.firebaseapp.com',
    storageBucket: 'zylu-employee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9iW9d-I0s7zesJXwu6yFF-QnIIPmlPYY',
    appId: '1:761920059803:android:f117b332eaf50c8f7b493e',
    messagingSenderId: '761920059803',
    projectId: 'zylu-employee',
    storageBucket: 'zylu-employee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXTfumrVkO3G0wXQHmnREAZz84bJBoWss',
    appId: '1:761920059803:ios:4b2979d60128b05b7b493e',
    messagingSenderId: '761920059803',
    projectId: 'zylu-employee',
    storageBucket: 'zylu-employee.appspot.com',
    iosBundleId: 'com.example.zyluFlutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXTfumrVkO3G0wXQHmnREAZz84bJBoWss',
    appId: '1:761920059803:ios:67d7feae30814e8c7b493e',
    messagingSenderId: '761920059803',
    projectId: 'zylu-employee',
    storageBucket: 'zylu-employee.appspot.com',
    iosBundleId: 'com.example.zyluFlutterTask.RunnerTests',
  );
}
